tabPanel("Sen_Cntls",
         wellPanel(
           h5("SV1"),
           conditionalPanel(condition = "input.param1.indexOf('1') > -1", 
                            sliderInput(inputId = "sv1_a",
                                        label = "A^1/2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('2') > -1",
                            sliderInput(inputId = "sv1_m",
                                        label = "M_0",
                                        min = 20,
                                        max = 200,
                                        value = 45, 
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('3') > -1",
                            sliderInput(inputId = "sv1_e",
                                        label = "e",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('4') > -1",
                            sliderInput(inputId = "sv1_omega",
                                        label = "omega",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('5') > -1",
                            sliderInput(inputId = "sv1_omega_0",
                                        label = "omega_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('6') > -1",
                            sliderInput(inputId = "sv1_i_0",
                                        label = "i_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('7') > -1",
                            sliderInput(inputId = "sv1_t_toe",
                                        label = "t_toe",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('8') > -1",
                            sliderInput(inputId = "sv1_CUC",
                                        label = "CUC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('9') > -1",
                            sliderInput(inputId = "sv1_CUS",
                                        label = "CUS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('10') > -1",
                            sliderInput(inputId = "sv1_CRC",
                                        label = "CRC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('11') > -1",
                            sliderInput(inputId = "sv1_CRS",
                                        label = "CRS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('12') > -1",
                            sliderInput(inputId = "sv1_CIC",
                                        label = "CIC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('13') > -1",
                            sliderInput(inputId = "sv1_CIS",
                                        label = "CIS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('14') > -1",
                            sliderInput(inputId = "sv1_PR1",
                                        label = "PR1",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('15') > -1",
                            sliderInput(inputId = "sv1_PR2",
                                        label = "PR2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('16') > -1",
                            sliderInput(inputId = "sv1_PR3",
                                        label = "PR3",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param1.indexOf('17') > -1",
                            sliderInput(inputId = "sv1_PR4",
                                        label = "PR4",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           )
         ), #end of sliders for Param 1
         
         wellPanel(
           h5("SV2"),
           conditionalPanel(condition = "input.param2.indexOf('1') > -1", 
                            sliderInput(inputId = "sv2_A^1/2",
                                        label = "A^1/2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('2') > -1",
                            sliderInput(inputId = "sv2_M_0",
                                        label = "M_0",
                                        min = 20,
                                        max = 200,
                                        value = 45, 
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('3') > -1",
                            sliderInput(inputId = "sv2_e",
                                        label = "e",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('4') > -1",
                            sliderInput(inputId = "sv2_omega",
                                        label = "omega",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('5') > -1",
                            sliderInput(inputId = "sv2_omega_0",
                                        label = "omega_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('6') > -1",
                            sliderInput(inputId = "sv2_i_0",
                                        label = "i_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('7') > -1",
                            sliderInput(inputId = "sv2_t_toe",
                                        label = "t_toe",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('8') > -1",
                            sliderInput(inputId = "sv2_CUC",
                                        label = "CUC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('9') > -1",
                            sliderInput(inputId = "sv2_CUS",
                                        label = "CUS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('10') > -1",
                            sliderInput(inputId = "sv2_CRC",
                                        label = "CRC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('11') > -1",
                            sliderInput(inputId = "sv2_CRS",
                                        label = "CRS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('12') > -1",
                            sliderInput(inputId = "sv2_CIC",
                                        label = "CIC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('13') > -1",
                            sliderInput(inputId = "sv2_CIS",
                                        label = "CIS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('14') > -1",
                            sliderInput(inputId = "sv2_PR1",
                                        label = "PR1",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('15') > -1",
                            sliderInput(inputId = "sv2_PR2",
                                        label = "PR2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('16') > -1",
                            sliderInput(inputId = "sv2_PR3",
                                        label = "PR3",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param2.indexOf('17') > -1",
                            sliderInput(inputId = "sv2_PR4",
                                        label = "PR4",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           )
           
         ), #end of sliders for Param 2
         
         wellPanel(
           h5("SV3"),
           conditionalPanel(condition = "input.param3.indexOf('1') > -1", 
                            sliderInput(inputId = "sv3_A^1/2",
                                        label = "A^1/2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('2') > -1",
                            sliderInput(inputId = "sv3_M_0",
                                        label = "M_0",
                                        min = 20,
                                        max = 200,
                                        value = 45, 
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('3') > -1",
                            sliderInput(inputId = "sv3_e",
                                        label = "e",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('4') > -1",
                            sliderInput(inputId = "sv3_omega",
                                        label = "omega",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('5') > -1",
                            sliderInput(inputId = "sv3_omega_0",
                                        label = "omega_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('6') > -1",
                            sliderInput(inputId = "sv3_i_0",
                                        label = "i_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('7') > -1",
                            sliderInput(inputId = "sv3_t_toe",
                                        label = "t_toe",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('8') > -1",
                            sliderInput(inputId = "sv3_CUC",
                                        label = "CUC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('9') > -1",
                            sliderInput(inputId = "sv3_CUS",
                                        label = "CUS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('10') > -1",
                            sliderInput(inputId = "sv3_CRC",
                                        label = "CRC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('11') > -1",
                            sliderInput(inputId = "sv3_CRS",
                                        label = "CRS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('12') > -1",
                            sliderInput(inputId = "sv3_CIC",
                                        label = "CIC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('13') > -1",
                            sliderInput(inputId = "sv3_CIS",
                                        label = "CIS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('14') > -1",
                            sliderInput(inputId = "sv3_PR1",
                                        label = "PR1",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('15') > -1",
                            sliderInput(inputId = "sv3_PR2",
                                        label = "PR2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('16') > -1",
                            sliderInput(inputId = "sv3_PR3",
                                        label = "PR3",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param3.indexOf('17') > -1",
                            sliderInput(inputId = "sv3_PR4",
                                        label = "PR4",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           )
           
         ), #end of sliders for Param 3
         
         wellPanel(
           h5("SV4"),
           conditionalPanel(condition = "input.param4.indexOf('1') > -1", 
                            sliderInput(inputId = "sv4_A^1/2",
                                        label = "A^1/2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('2') > -1",
                            sliderInput(inputId = "sv4_M_0",
                                        label = "M_0",
                                        min = 20,
                                        max = 200,
                                        value = 45, 
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('3') > -1",
                            sliderInput(inputId = "sv4_e",
                                        label = "e",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('4') > -1",
                            sliderInput(inputId = "sv4_omega",
                                        label = "omega",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('5') > -1",
                            sliderInput(inputId = "sv4_omega_0",
                                        label = "omega_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('6') > -1",
                            sliderInput(inputId = "sv4_i_0",
                                        label = "i_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('7') > -1",
                            sliderInput(inputId = "sv4_t_toe",
                                        label = "t_toe",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('8') > -1",
                            sliderInput(inputId = "sv4_CUC",
                                        label = "CUC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('9') > -1",
                            sliderInput(inputId = "sv4_CUS",
                                        label = "CUS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('10') > -1",
                            sliderInput(inputId = "sv4_CRC",
                                        label = "CRC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('11') > -1",
                            sliderInput(inputId = "sv4_CRS",
                                        label = "CRS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('12') > -1",
                            sliderInput(inputId = "sv4_CIC",
                                        label = "CIC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('13') > -1",
                            sliderInput(inputId = "sv4_CIS",
                                        label = "CIS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('14') > -1",
                            sliderInput(inputId = "sv4_PR1",
                                        label = "PR1",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('15') > -1",
                            sliderInput(inputId = "sv4_PR2",
                                        label = "PR2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('16') > -1",
                            sliderInput(inputId = "sv4_PR3",
                                        label = "PR3",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param4.indexOf('17') > -1",
                            sliderInput(inputId = "sv4_PR4",
                                        label = "PR4",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           )
          
           
         ), #end of sliders for Param 4
         
         wellPanel(
           h5("SV5"),
           conditionalPanel(condition = "input.param5.indexOf('1') > -1", 
                            sliderInput(inputId = "sv5_A^1/2",
                                        label = "A^1/2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('2') > -1",
                            sliderInput(inputId = "sv5_M_0",
                                        label = "M_0",
                                        min = 20,
                                        max = 200,
                                        value = 45, 
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('3') > -1",
                            sliderInput(inputId = "sv5_e",
                                        label = "e",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('4') > -1",
                            sliderInput(inputId = "sv5_omega",
                                        label = "omega",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('5') > -1",
                            sliderInput(inputId = "sv5_omega_0",
                                        label = "omega_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('6') > -1",
                            sliderInput(inputId = "sv5_i_0",
                                        label = "i_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('7') > -1",
                            sliderInput(inputId = "sv5_t_toe",
                                        label = "t_toe",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('8') > -1",
                            sliderInput(inputId = "sv5_CUC",
                                        label = "CUC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('9') > -1",
                            sliderInput(inputId = "sv5_CUS",
                                        label = "CUS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('10') > -1",
                            sliderInput(inputId = "sv5_CRC",
                                        label = "CRC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('11') > -1",
                            sliderInput(inputId = "sv5_CRS",
                                        label = "CRS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('12') > -1",
                            sliderInput(inputId = "sv5_CIC",
                                        label = "CIC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('13') > -1",
                            sliderInput(inputId = "sv5_CIS",
                                        label = "CIS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('14') > -1",
                            sliderInput(inputId = "sv5_PR1",
                                        label = "PR1",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('15') > -1",
                            sliderInput(inputId = "sv5_PR2",
                                        label = "PR2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('16') > -1",
                            sliderInput(inputId = "sv5_PR3",
                                        label = "PR3",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('17') > -1",
                            sliderInput(inputId = "sv5_PR4",
                                        label = "PR4",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           )
           
         ), #end of sliders for Param 5
         
         wellPanel(
           h5("SV6"),
           conditionalPanel(condition = "input.param6.indexOf('1') > -1", 
                            sliderInput(inputId = "sv6_A^1/2",
                                        label = "A^1/2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('2') > -1",
                            sliderInput(inputId = "sv6_M_0",
                                        label = "M_0",
                                        min = 20,
                                        max = 200,
                                        value = 45, 
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('3') > -1",
                            sliderInput(inputId = "sv6_e",
                                        label = "e",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('4') > -1",
                            sliderInput(inputId = "sv6_omega",
                                        label = "omega",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('5') > -1",
                            sliderInput(inputId = "sv6_omega_0",
                                        label = "omega_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('6') > -1",
                            sliderInput(inputId = "sv6_i_0",
                                        label = "i_0",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('7') > -1",
                            sliderInput(inputId = "sv6_t_toe",
                                        label = "t_toe",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('8') > -1",
                            sliderInput(inputId = "sv6_CUC",
                                        label = "CUC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('9') > -1",
                            sliderInput(inputId = "sv6_CUS",
                                        label = "CUS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('10') > -1",
                            sliderInput(inputId = "sv6_CRC",
                                        label = "CRC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('11') > -1",
                            sliderInput(inputId = "sv6_CRS",
                                        label = "CRS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param6.indexOf('12') > -1",
                            sliderInput(inputId = "sv6_CIC",
                                        label = "CIC",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('13') > -1",
                            sliderInput(inputId = "sv5_CIS",
                                        label = "CIS",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('14') > -1",
                            sliderInput(inputId = "sv5_PR1",
                                        label = "PR1",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('15') > -1",
                            sliderInput(inputId = "sv5_PR2",
                                        label = "PR2",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('16') > -1",
                            sliderInput(inputId = "sv5_PR3",
                                        label = "PR3",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           ),
           conditionalPanel(condition = "input.param5.indexOf('17') > -1",
                            sliderInput(inputId = "sv5_PR4",
                                        label = "PR4",
                                        min = 20,
                                        max = 200,
                                        value = 45,
                                        step = 10)
           )
           
         ) #end of sliders for Param 6
         
         
)